version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysqlDB
      MYSQL_USERNAME: test
      MYSQL_PASSWORD: 1234
    volumes:
      - 'mysqldata:/var/lib/mysql'

volumes:
  mysqldata: